onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {top level signals}
add wave -noupdate /datapath_all_tb/datap/CLK
add wave -noupdate /datapath_all_tb/datap/Reset
add wave -noupdate -divider <NULL>
add wave -noupdate /datapath_all_tb/CLKtb
add wave -noupdate /datapath_all_tb/Resettb
add wave -noupdate /datapath_all_tb/datap/FROM_IR
add wave -noupdate /datapath_all_tb/datap/FROM_SEXT5
add wave -noupdate /datapath_all_tb/datap/FROM_SEXT8
add wave -noupdate /datapath_all_tb/datap/FROM_SEXT10
add wave -noupdate /datapath_all_tb/datap/FROM_ZEXT7
add wave -noupdate /datapath_all_tb/datap/FROM_SEXT4
add wave -noupdate /datapath_all_tb/datap/LD_REG1
add wave -noupdate /datapath_all_tb/datap/LD_IR
add wave -noupdate /datapath_all_tb/datap/DR_SEL
add wave -noupdate /datapath_all_tb/datap/FROM_BUS
add wave -noupdate /datapath_all_tb/datap/SR1_SEL
add wave -noupdate /datapath_all_tb/datap/SR2_SEL
add wave -noupdate /datapath_all_tb/datap/FROM_SR1_RF
add wave -noupdate /datapath_all_tb/datap/FROM_SR2_RF
add wave -noupdate /datapath_all_tb/datap/FROM_SR2_MUX
add wave -noupdate /datapath_all_tb/datap/ALU_SEL
add wave -noupdate /datapath_all_tb/datap/FROM_ALU
add wave -noupdate /datapath_all_tb/datap/GATE_ALU1
add wave -noupdate /datapath_all_tb/datap/ADDR1_MUX_SEL
add wave -noupdate /datapath_all_tb/datap/ADDR2_MUX_SEL
add wave -noupdate /datapath_all_tb/datap/SR2MUX_SEL
add wave -noupdate /datapath_all_tb/datap/ZERO
add wave -noupdate /datapath_all_tb/datap/FROM_PCMUX
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2MUX
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR1MUX
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNTRBUS
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNTRINC
add wave -noupdate /datapath_all_tb/datap/FROM_PC1
add wave -noupdate /datapath_all_tb/datap/FROM_BUS_NZP
add wave -noupdate /datapath_all_tb/datap/FROM_NZP
add wave -noupdate /datapath_all_tb/datap/FROM_ADDER
add wave -noupdate /datapath_all_tb/datap/FROM_MARMUX
add wave -noupdate /datapath_all_tb/datap/MEM_EN
add wave -noupdate /datapath_all_tb/datap/FROM_MDR
add wave -noupdate /datapath_all_tb/datap/FROM_MEM
add wave -noupdate /datapath_all_tb/datap/FROM_MAR
add wave -noupdate /datapath_all_tb/datap/LD_PC
add wave -noupdate /datapath_all_tb/datap/LD_MAR
add wave -noupdate /datapath_all_tb/datap/LD_MEM
add wave -noupdate /datapath_all_tb/datap/LD_MDR
add wave -noupdate /datapath_all_tb/datap/LD_MARMUX
add wave -noupdate /datapath_all_tb/datap/LD_CC
add wave -noupdate /datapath_all_tb/datap/PCMUX_SEL
add wave -noupdate /datapath_all_tb/datap/GATE_PC1
add wave -noupdate /datapath_all_tb/datap/GATE_MAR
add wave -noupdate /datapath_all_tb/datap/GATE_MDR1
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/CLK
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/Reset
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/En
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/OP_A
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/OP_Q
add wave -noupdate /datapath_all_tb/datap/Bus_to_IR/my_sig
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT4/CLK
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT4/Reset
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT4/OP_A
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT4/OP_Q
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT4/my_sig
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT5/CLK
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT5/Reset
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT5/OP_A
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT5/OP_Q
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT5/my_sig
add wave -noupdate /datapath_all_tb/datap/IR_TO_ZEXT7/CLK
add wave -noupdate /datapath_all_tb/datap/IR_TO_ZEXT7/Reset
add wave -noupdate /datapath_all_tb/datap/IR_TO_ZEXT7/OP_A
add wave -noupdate /datapath_all_tb/datap/IR_TO_ZEXT7/OP_Q
add wave -noupdate /datapath_all_tb/datap/IR_TO_ZEXT7/my_sig
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT8/CLK
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT8/Reset
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT8/OP_A
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT8/OP_Q
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT8/my_sig
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT10/CLK
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT10/Reset
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT10/OP_A
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT10/OP_Q
add wave -noupdate /datapath_all_tb/datap/IR_TO_SEXT10/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/LD_REG
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/DR
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/SR1
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/SR2
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/OP_Q1
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/OP_Q2
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/sEn
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/sFF
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(0)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(1)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(2)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(3)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(4)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(5)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(6)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/En
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_REG_FILE/g0(7)/regh0/my_sig
add wave -noupdate /datapath_all_tb/datap/SR2MUX_TO_ALU/a_0
add wave -noupdate /datapath_all_tb/datap/SR2MUX_TO_ALU/a_1
add wave -noupdate /datapath_all_tb/datap/SR2MUX_TO_ALU/y
add wave -noupdate /datapath_all_tb/datap/SR2MUX_TO_ALU/sel
add wave -noupdate /datapath_all_tb/datap/FROM_ALU_TO_BUS/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_ALU_TO_BUS/OP_B
add wave -noupdate /datapath_all_tb/datap/FROM_ALU_TO_BUS/sel
add wave -noupdate /datapath_all_tb/datap/FROM_ALU_TO_BUS/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_ALU_TO_BUS/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_GALU_TO_BUS/En
add wave -noupdate /datapath_all_tb/datap/FROM_GALU_TO_BUS/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_GALU_TO_BUS/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/a_0
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/a_1
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/a_2
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/a_3
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/y
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR2_MUX/sel
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR1_MUX/a_0
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR1_MUX/a_1
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR1_MUX/y
add wave -noupdate /datapath_all_tb/datap/FROM_ADDR1_MUX/sel
add wave -noupdate /datapath_all_tb/datap/FROM_ADDER_16/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_ADDER_16/OP_B
add wave -noupdate /datapath_all_tb/datap/FROM_ADDER_16/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_PC_MUX/a_0
add wave -noupdate /datapath_all_tb/datap/FROM_PC_MUX/a_1
add wave -noupdate /datapath_all_tb/datap/FROM_PC_MUX/a_2
add wave -noupdate /datapath_all_tb/datap/FROM_PC_MUX/y
add wave -noupdate /datapath_all_tb/datap/FROM_PC_MUX/sel
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/En
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/OP_Z
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/your_sig
add wave -noupdate /datapath_all_tb/datap/FROM_PC_CNT/my_sig
add wave -noupdate /datapath_all_tb/datap/FROM_PC_TO_BUS/En
add wave -noupdate /datapath_all_tb/datap/FROM_PC_TO_BUS/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_PC_TO_BUS/OP_Q
add wave -noupdate /datapath_all_tb/datap/MARMUX_TO_TRI/a_0
add wave -noupdate /datapath_all_tb/datap/MARMUX_TO_TRI/a_1
add wave -noupdate /datapath_all_tb/datap/MARMUX_TO_TRI/y
add wave -noupdate /datapath_all_tb/datap/MARMUX_TO_TRI/sel
add wave -noupdate /datapath_all_tb/datap/FROM_MARM_TO_BUS/En
add wave -noupdate /datapath_all_tb/datap/FROM_MARM_TO_BUS/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_MARM_TO_BUS/OP_Q
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/En
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/BUS_IN
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/MAR_OUT
add wave -noupdate /datapath_all_tb/datap/FROM_MAR_TO_MEM/MAR_DATA_OUT
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/mem_wr_rd_add
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/data_in
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/data_out
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/read_write_En
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/mem_En
add wave -noupdate /datapath_all_tb/datap/FROM_MEM_TO_MDR/sdata_out
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/CLK
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/En
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/Reset
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/BUS_IN
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/MEM_IN
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/MDR_OUT
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BORM/MDR_DATA
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BUS/En
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BUS/OP_A
add wave -noupdate /datapath_all_tb/datap/FROM_MDR_TO_BUS/OP_Q
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/CLK
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/Reset
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/En
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/OP_A
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/OP_Q
add wave -noupdate /datapath_all_tb/datap/NZP_TO_FSM/sOP_Q
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/CLK
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/Reset
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/OUT_FROM_IR
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/FROM_NZP
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_IR
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_MARMUX
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_REG1
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_PC
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_CC
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_MAR
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_MDR
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/LD_MEM
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/GATE_PC1
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/GATE_MAR
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/GATE_ALU1
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/GATE_MDR1
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/ADDR2_MUX_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/ADDR1_MUX_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/SR1_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/SR2_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/DR_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/SR2MUX_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/PCMUX_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/ALU_SEL
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/MEM_En
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/cpu_state
add wave -noupdate /datapath_all_tb/datap/FSM_TO_DP/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 286
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {729 ns}
